# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: NIH GHMP (Prod) - Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          cd ./default-assets-package
          npm install
          npm run build
          cd ..
          npm run test --if-present
          
      - name: get orgs from graphql
        run: |
          gh api graphql -f ent=nih -f query='query($ent: String!) {
           enterprise(slug: $ent) {
             organizations(first: 100) {
               nodes {
                 description
                 login
                 databaseId
                 id
                 name
               }
             }
           }
          }' >> raw.json
          cat raw.json
        env:
          GITHUB_TOKEN: ${{ secrets.ENT_READ_PAT}}

      - name: run powershell script to create env orgs json
        run: |
          ./.github/scripts/Create-EnvOrgs.ps1
          cat orgs.json
          ls
        shell: pwsh

      - name: check file
        run: |
          cat orgs.json
          ls -lah
          rm env-orgs.json
          cat orgs.json >> env-orgs.json
          cat env-orgs.json
          
      - name: zip application folders
        run: |
          echo $PWD
          ls -lah
          cd ..
          echo $PWD
          ls -lah
          tar -czf output.tar.gz ./github-portal
          ls -lah

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: /home/runner/work/github-portal/output.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
    
      - name: Unpack tar
        run: |
          tar -xf output.tar.gz
          ls -lah

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nihgithubportal'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_990190F22A5149AC859307273BAE196C }}
          package: .
